// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6IxGl2a9xGpkpFkvuEije-7nRTB1cmFU',
    appId: '1:55318025403:web:4a49fe068e34040a11859e',
    messagingSenderId: '55318025403',
    projectId: 'piwo-4487e',
    authDomain: 'piwo-4487e.firebaseapp.com',
    databaseURL:
        'https://piwo-4487e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'piwo-4487e.appspot.com',
    measurementId: 'G-LEWMQNTD0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChvrbrm_ky1ssjhuoNtt0acNHVN2-cNww',
    appId: '1:55318025403:android:53e9b513e163c47e11859e',
    messagingSenderId: '55318025403',
    projectId: 'piwo-4487e',
    databaseURL:
        'https://piwo-4487e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'piwo-4487e.appspot.com',
  );
}
